#!/usr/bin/env python3
"""Generate npc-sprite-manifest.json + portrait-sprite-manifest.json from
public/sprites/npc/*.png and public/sprites/portraits/*.png.
BootScene preloads everything listed; runtime falls back to placeholders
if a texture is missing (same contract as battle-sprite-manifest.json)."""
import json, os

BASE = '/home/min/dev/soren-jrpg/public/sprites'
OUT = '/home/min/dev/soren-jrpg/src/game'

def manifest(subdir):
    d = os.path.join(BASE, subdir)
    if not os.path.isdir(d):
        return []
    return sorted(f[:-4] for f in os.listdir(d) if f.endswith('.png'))

npcs = manifest('npc')
portraits = manifest('portraits')
json.dump({
    "_comment": "Generated by design-spike/gen_npc_manifest.py — field NPC sprite keys",
    "npcs": npcs,
}, open(os.path.join(OUT, 'npc-sprite-manifest.json'), 'w'), indent=2)
json.dump({
    "_comment": "Generated by design-spike/gen_npc_manifest.py — dialogue portrait keys (48x48)",
    "portraits": portraits,
}, open(os.path.join(OUT, 'portrait-sprite-manifest.json'), 'w'), indent=2)
print(f"npc manifest: {len(npcs)} entries, portraits: {len(portraits)} entries")