#!/usr/bin/env python3
"""Generate the battle-sprite manifest (src/game/battle-sprite-manifest.json)
from public/sprites/battle/*.png. Run after generating/processing sprites.
BootScene reads this at build time via vite import; BattleScene checks
texture existence at runtime anyway (manifest is an optimization + list)."""
import json, os

PUB = '/home/min/dev/soren-jrpg/public/sprites/battle'
files = sorted(f[:-4] for f in os.listdir(PUB) if f.endswith('.png'))

manifest = {
    "_comment": "Generated by design-spike/gen_manifest.py — enemy/party battle sprite keys available",
    "enemies": [f for f in files if not f.startswith(('soren_battle', 'aria_battle', 'kael_battle', 'aldric_battle'))],
    "party": {},
}
for name, key in [("Soren", "soren_battle"), ("Aria", "aria_battle"), ("Kael", "kael_battle"), ("Aldric", "aldric_battle")]:
    if key in files:
        manifest["party"][name] = key
out = '/home/min/dev/soren-jrpg/src/game/battle-sprite-manifest.json'
json.dump(manifest, open(out, 'w'), indent=2)
print(f"manifest: {len(manifest['enemies'])} enemies + 4 party entries -> {out}")